# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: f9a46901fdf8518fb0448dde49408911635c0a063d7db28727db91da57c644d53157b75265b6106c8181d2156d7ed48a5adbca45d624ac3279fd2b9f0e7eabc7

test:
  secret_key_base: a595f1a456f18bbab8f79b12376a73939808c7b3362c090b7609ae95324358f5abcc61b8b480698c0020b29a25e93bbef966614d89099773367f81a34ca705c6

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
